create a useFull page for learning english
peaksoft-school/bilingual-js11 pull request #22
Opened 2024-01-15 13:52 UTC by IsaevNurislam

2024-01-15 15:29 UTC, mamy1ova commented on src/components/UsefulVideos.jsx
> +const videos = [
Этот массив должен быть в папке utils => constants

2024-01-15 15:47 UTC, Rabiya46 commented on src/components/UsefulVideos.jsx
> +const videos = [
С большими буквами

2024-01-15 15:47 UTC, Rabiya46 commented on src/components/UsefulVideos.jsx
> +   return (
return убери

2024-01-15 15:47 UTC, Rabiya46 commented on src/components/UsefulVideos.jsx
> +               {videos.map((item) => (
destruction item

2024-01-17 06:21 UTC, AziatAbd requested changes

2024-01-17 06:21 UTC, AziatAbd commented on src/components/UsefulVideos.jsx
> +const StyledUsefulVideos = () => (
убери styled

2024-01-17 06:21 UTC, AziatAbd commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "off",
зачем off'нул? Верни

2024-01-17 06:21 UTC, AziatAbd commented on src/components/UsefulVideos.jsx
откройте папку landing-page и храните все файлы которые нужны для главной страницы

2024-01-17 13:03 UTC, IsaevNurislam commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "off",
bez etogo moi importy dayut oshibku , daje esli ya delayu vse pravilno , import { DefaultPlayer } from 'react-html5video'
import 'react-html5video/dist/styles.css'
eto chast vsegda dayet oshibku

2024-01-17 13:35 UTC, AziatAbd commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "off",
перезагрузи vscode, и сам заново импортируй

2024-01-18 08:09 UTC, merged