create component partners
peaksoft-school/bilingual-js11 pull request #24
Opened 2024-01-16 14:28 UTC by ironmen05

2024-01-18 08:25 UTC, Rabiya46 commented on src/App.jsx
> +import React from 'react'
убери react

2024-01-18 08:25 UTC, Rabiya46 commented on src/components/Partners.jsx
> +                           />
destruction map

2024-01-25 04:51 UTC, Rabiya46 commented on src/App.jsx
> -
почему App.css удалил?

2024-01-25 04:51 UTC, Rabiya46 commented on src/utils/constants/PartnersData.js
> +export default PartnersData
pull сделай и перемести это в index.js

2024-01-26 05:02 UTC, AziatAbd requested changes

2024-01-26 05:02 UTC, AziatAbd commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "off",
верни обратно, не оффай

2024-01-26 05:03 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js11/assets/115453436/bf93dc72-f79d-400d-9eb5-6ef953dc2a7b)

убери стрелку

2024-01-27 08:34 UTC, merged