Feature/modal
peaksoft-school/bilingual-js11 pull request #41
Opened 2024-01-29 09:43 UTC by IsaevNurislam

2024-01-29 13:17 UTC, Rabiya46 commented on src/App.jsx
>  }
Очисти App

2024-01-29 13:17 UTC, Rabiya46 commented on src/components/UI/modals/ModalLogOut.jsx
> +   '& .Text': {
с маленькой пиши

2024-01-29 13:17 UTC, Rabiya46 commented on src/components/UI/modals/ModalDelete.jsx
> +   '& .Text': {
с маленькой буквой

2024-01-29 13:17 UTC, Rabiya46 commented on src/components/UI/modals/ModalDelete.jsx
> +   '& .Title': {
с маленькой буквой

2024-01-30 10:06 UTC, mamy1ova commented on src/components/UI/modals/ModalDelete.jsx
> +      <Container>
переименуй Container на StyledContainer

2024-01-30 10:06 UTC, mamy1ova commented on src/components/UI/modals/ModalDelete.jsx
> +               <FalseIcon className="redCrossImage" />
переименуй className redCrossImage нужно писать через kebab-case( - )

2024-01-30 10:06 UTC, mamy1ova commented on src/components/UI/modals/ModalDelete.jsx
> +               <Box className="containerBtns">
переименуй className containerBtns нужно писать через kebab-case( - )

2024-01-30 10:12 UTC, mamy1ova commented on src/components/UI/modals/ModalLogOut.jsx
> +            <Box className="buttons">
не забывай отступы

2024-01-30 10:12 UTC, mamy1ova commented on src/components/UI/modals/ModalSave.jsx
> +      <Container>
переименуй Container на StyledContainer

2024-01-30 10:12 UTC, mamy1ova commented on src/components/UI/modals/ModalSave.jsx
> +               <Box className="conForm">
переименуй className conForm нужно писать через kebab-case( - )  и логичный болсун

2024-01-30 10:12 UTC, mamy1ova commented on src/components/UI/modals/ModalSave.jsx
> +                     <Typography className="trueOption">
поменяй className нужно писать через kebab-case( - )

2024-01-30 10:12 UTC, mamy1ova commented on src/components/UI/modals/ModalSave.jsx
> +                  <Box className="conOfBtns">
поменяй className нужно писать через kebab-case( - )

2024-02-03 06:07 UTC, AziatAbd requested changes

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalDelete.jsx
> +   const handleIsVisible = () => setIsVisidle((prev) => !prev)
через пропс келсин

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalDelete.jsx
> +         <StyledOpenButton onClick={handleIsVisible}>DELETE</StyledOpenButton>
зачем здесь кнопка? Убери

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalSave.jsx
> +   const handleIsVisible = () => setIsVisidle((prev) => !prev)
здесь тоже

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalLogOut.jsx
> +const ModalLogOut = ({ onLogOut }) => {
это не modalLogOut, а просто modal

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalLogOut.jsx
> +               <Button onClick={onLogOut}>Yes</Button>
удали всё содержимое, он должен принимать только children

2024-02-03 06:07 UTC, AziatAbd commented on src/components/UI/modals/ModalSave.jsx
> +               </Box>
![image](https://github.com/peaksoft-school/bilingual-js11/assets/115453436/b8bc1bc5-44b4-4972-bb5d-c03e3d8c8a12)
![image](https://github.com/peaksoft-school/bilingual-js11/assets/115453436/66e139b5-2320-4bdf-adb7-12c75e711956)

один из них SelectRealEnglishWord а другой ListenAndSelectRealEnglishWord, дай условие для них если если тру то первый если фалс то второй

2024-02-03 07:55 UTC, merged