Feature/type what you hear
peaksoft-school/bilingual-js11 pull request #62
Opened 2024-03-06 13:24 UTC by IsaevNurislam

2024-03-08 09:23 UTC, AziatAbd requested changes

2024-03-08 09:23 UTC, AziatAbd commented on src/store/slice/user/userSlice.js
> +      },
answer дегенди каяктан таптын? если initialState'те жок болсо

2024-03-08 09:23 UTC, AziatAbd commented on src/store/slice/user/userSlice.js
слайсты сен кошо турган болдунбу? или Рабия?

2024-03-08 09:23 UTC, AziatAbd commented on src/pages/user/tests/types/TypeWhatYouHear.jsx
> +            }
если replaysLeft 0'го барабар болсо то бир текст чыгарып кой чтобы юзер тушунуш учун

2024-03-08 09:30 UTC, IsaevNurislam commented on src/store/slice/user/userSlice.js
Рабия

2024-03-08 11:38 UTC, AziatAbd requested changes

2024-03-08 11:38 UTC, AziatAbd commented on src/App.jsx
> +const App = () => <TypeWhatYouHearss />
app кайтар

2024-03-08 11:38 UTC, AziatAbd commented on src/store/slice/user/userSlice.js
анда очуруп ташта

2024-03-13 06:25 UTC, AziatAbd requested changes

2024-03-13 06:25 UTC, AziatAbd commented on src/store/slice/user/userSlice.js
слайсты полностью очуруп ташта, Рабия озу кошот

2024-03-15 05:22 UTC, merged